name: Android CI Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: NLChat  # 确保代码被检出到NLChat目录

    - name: Set up JDK 17
      id: setup-java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=${{ steps.setup-java.outputs.path }}" >> $GITHUB_ENV

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 'current'  # 使用最新的 Gradle 版本

    - name: Grant execute permission for gradlew
      run: chmod +x NLChat/gradlew

    - name: Build Project
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}  # 显式设置 JAVA_HOME
      run: |
        echo "JAVA_HOME=${JAVA_HOME}"  # 确认 JAVA_HOME 已设置
        cd NLChat
        ./gradlew assembleRelease

    - name: Sign
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: NLChat/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: List files in release directory
      run: ls -R NLChat/app/build/outputs/apk/release

    - name: Upload Signed APK
      uses: actions/upload-artifact@v3
      with:
        name: signed-apk
        path: NLChat/app/build/outputs/apk/release/app-release-unsigned-signed.apk

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: NLChat  # 确保代码被检出到NLChat目录

    - name: Download Signed APK
      uses: actions/download-artifact@v3
      with:
        name: signed-apk
        path: NLChat/app/build/outputs/apk/release

    - name: Release Ready
      run: |
        if [ -f "NLChat/app/build/outputs/apk/release/app-release-unsigned-signed.apk" ]; then
          mv NLChat/app/build/outputs/apk/release/app-release-unsigned-signed.apk NLChat_${{ github.ref_name }}.apk
        else
          echo "Error: APK file not found!"
          exit 1
        fi

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "NLChat_${{ github.ref_name }}.apk"
        token: ${{ secrets.GITHUB_TOKEN }}  # 使用 PAT
        generateReleaseNotes: true

    - name: Get Commit Message
      id: get_commit_message
      run: |
        cd NLChat
        echo "COMMIT_MESSAGE=$(git log -2 --pretty=%B)" >> $GITHUB_ENV
      continue-on-error: true

    - name: Create or Update Release Notes
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: |
          ## 测试内容1
          ${{ env.COMMIT_MESSAGE }}
          ## 测试内容2
          Commit ID: ${{ github.event.head_commit.id }}
          Commit Message: ${{ github.event.head_commit.message }}
          Commit Timestamp: ${{ github.event.head_commit.timestamp }}
          Author Name: ${{ github.event.head_commit.author.name }}
          Author Email: ${{ github.event.head_commit.author.email }}
          Committer Name: ${{ github.event.head_commit.committer.name }}
          Committer Email: ${{ github.event.head_commit.committer.email }}
          Commit URL: ${{ github.event.head_commit.url }}
          ## 测试内容3
          Pull Request URL: ${{ github.event.pull_request.url }}
          Pull Request ID: ${{ github.event.pull_request.id }}
          Pull Request Number: ${{ github.event.pull_request.number }}
          Pull Request Title: ${{ github.event.pull_request.title }}
          Pull Request Body: ${{ github.event.pull_request.body }}
          Author Login: ${{ github.event.pull_request.user.login }}
          Author ID: ${{ github.event.pull_request.user.id }}
          Source Branch: ${{ github.event.pull_request.head.ref }}
          Source SHA: ${{ github.event.pull_request.head.sha }}
          Target Branch: ${{ github.event.pull_request.base.ref }}
          Target SHA: ${{ github.event.pull_request.base.sha }}
          Is Merged: ${{ github.event.pull_request.merged }}
          Merge Commit SHA: ${{ github.event.pull_request.merge_commit_sha }}
          ## 测试内容4
          Commit ID: ${{ github.event.commit.id }}
          Commit Message: ${{ github.event.commit.message }}
          Commit Timestamp: ${{ github.event.commit.timestamp }}
          Author Name: ${{ github.event.commit.author.name }}
          Author Email: ${{ github.event.commit.author.email }}
          Commit URL: ${{ github.event.commit.url }}
          ## 测试内容5
          Committer Name: ${{ github.event.commit.committer.name }}
          Committer Email: ${{ github.event.commit.committer.email }}
          ## 测试内容6
          Pull Request Action: ${{ github.event.action }}
          ## 测试内容7
          ## 测试内容8
          ${{ steps.get_commit_message.outputs.COMMIT_MESSAGE }}
          ## 测试内容4
          ## What's Changed for recent commits
          ## What's Changed for recent commits
          ## New Contributors
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用环境变量
      continue-on-error: true
  
  multi-platform-test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        api-level: [28, 29, 31, 33]  # 你可以根据需要调整 API 级别
        target: [default, google_apis]
        arch: [x86_64, arm64-v8a]  # 你可以根据需要调整架构
        include:
          - api-level: 29
            target: default
            arch: x86_64
          - api-level: 29
            target: default
            arch: arm64-v8a
          - api-level: 29
            target: google_apis
            arch: arm64-v8a
          - api-level: 31
            target: default
            arch: x86_64
          - api-level: 31
            target: google_apis
            arch: x86_64
          - api-level: 31
            target: google_apis
            arch: arm64-v8a
          - api-level: 33
            target: default
            arch: x86_64
          - api-level: 33
            target: google_apis
            arch: arm64-v8a

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedAndroidTest --stacktrace
