name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Commit Message
      id: get_commit_message
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        DECODED_COMMIT_MESSAGE=$(echo $COMMIT_MESSAGE | jq -sRr @uri | python3 -c "import sys, urllib.parse as ul; print(ul.unquote(sys.stdin.read()))")
        echo "COMMIT_MESSAGE=$DECODED_COMMIT_MESSAGE" >> $GITHUB_ENV
      continue-on-error: true

    - name: Display Information
      run: |
        echo "## 测试内容1"
        echo "${{ env.COMMIT_MESSAGE }}"
        echo "## 测试内容2"
        echo "Commit ID: ${{ github.event.head_commit.id }}"
        echo "Commit Message: ${{ github.event.head_commit.message }}"
        echo "Commit Timestamp: ${{ github.event.head_commit.timestamp }}"
        echo "Author Name: ${{ github.event.head_commit.author.name }}"
        echo "Author Email: ${{ github.event.head_commit.author.email }}"
        echo "Committer Name: ${{ github.event.head_commit.committer.name }}"
        echo "Committer Email: ${{ github.event.head_commit.committer.email }}"
        echo "Commit URL: ${{ github.event.head_commit.url }}"
        echo "## 测试内容3"
        echo "Pull Request URL: ${{ github.event.pull_request.url }}"
        echo "Pull Request ID: ${{ github.event.pull_request.id }}"
        echo "Pull Request Number: ${{ github.event.pull_request.number }}"
        echo "Pull Request Title: ${{ github.event.pull_request.title }}"
        echo "Pull Request Body: ${{ github.event.pull_request.body }}"
        echo "Author Login: ${{ github.event.pull_request.user.login }}"
        echo "Author ID: ${{ github.event.pull_request.user.id }}"
        echo "Source Branch: ${{ github.event.pull_request.head.ref }}"
        echo "Source SHA: ${{ github.event.pull_request.head.sha }}"
        echo "Target Branch: ${{ github.event.pull_request.base.ref }}"
        echo "Target SHA: ${{ github.event.pull_request.base.sha }}"
        echo "Is Merged: ${{ github.event.pull_request.merged }}"
        echo "Merge Commit SHA: ${{ github.event.pull_request.merge_commit_sha }}"
        echo "## 测试内容4"
        echo "Commit ID: ${{ github.event.commit.id }}"
        echo "Commit Message: ${{ github.event.commit.message }}"
        echo "Commit Timestamp: ${{ github.event.commit.timestamp }}"
        echo "Author Name: ${{ github.event.commit.author.name }}"
        echo "Author Email: ${{ github.event.commit.author.email }}"
        echo "Commit URL: ${{ github.event.commit.url }}"
        echo "## 测试内容5"
        echo "Committer Name: ${{ github.event.commit.committer.name }}"
        echo "Committer Email: ${{ github.event.commit.committer.email }}"
        echo "## 测试内容6"
        echo "Pull Request Action: ${{ github.event.action }}"
        echo "## 测试内容7"
        echo "## 测试内容8"
        echo "${{ steps.get_commit_message.outputs.COMMIT_MESSAGE }}"
        echo "## 测试内容4"
        echo "## What's Changed for recent commits"
        echo "## What's Changed for recent commits"
        echo "## New Contributors"